name: Build VyOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: choice
        options:
          - equuleus
          - sagitta
          - circinus
          - current
      ref:
        description: Branch or tag to build, if different from version
        type: string

env:
  BUILD_ARCH: amd64

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build ISO
      run: |
        DOCKER_IMAGE="vyos/vyos-build:${{ github.event.inputs.version }}"
        docker pull $DOCKER_IMAGE
        git clone -b ${{ github.event.inputs.ref == '' && github.event.inputs.version || github.event.inputs.ref }} --single-branch https://github.com/vyos/vyos-build
        cp -r data vyos-build/
        cd vyos-build
        VYOS_VERSION=$(git describe --tags)
        echo "VYOS_VERSION=$VYOS_VERSION" >> $GITHUB_ENV
        BUILD_CMD=""
        COMMON_ARGS="--architecture ${{ env.BUILD_ARCH }} --build-type release --version \"$VYOS_VERSION\" --build-by \"${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com\""
        if [[ "${{ github.event.inputs.version }}" == "sagitta" ]]; then
          BUILD_CMD="sudo make clean && sudo ./build-vyos-image iso $COMMON_ARGS"
        elif [[ "${{ github.event.inputs.version }}" == "circinus" ]]; then
          BUILD_CMD="sudo make clean && sudo ./build-vyos-image generic $COMMON_ARGS"
        else
          BUILD_CMD="./configure $COMMON_ARGS && sudo make iso"
        fi
        docker run --rm -v $(pwd):/vyos -w /vyos --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0 $DOCKER_IMAGE \
          bash -c "$BUILD_CMD"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: VyOS ${{ env.VYOS_VERSION }}
        tag_name: ${{ env.VYOS_VERSION }}
        draft: false
        prerelease: false
        files: ${{ github.workspace }}/vyos-build/build/vyos-*.iso
